### ISSUE TITLE
Dependency name needs fixing

### ISSUE THREAD

**Issue by hythm7** [andinus/orion#1]
[this](https://github.com/andinus/orion/blob/master/META6.json#L14) dependency doesn't look right.  it has extra colon in the name.

`LWP::Simple::auth<...>`  probably needs to be `LWP::Simple:auth<...>`

**Comment by andinus** [comment]
Fixed with https://github.com/andinus/orion/commit/ecafbe5bb11cd056f4e6f11cd1d03af98a8eeb88

Also, turns out "auth" for `LWP::Simple` has changed to `zef:dwarring`.

Thank you!
